# Example of a TOML definition for a 27512

name = "27512"

type = "ROM"

[pinout]
# The address array defines the association of every address pin (starting with A0 and increasing) with the pin in the ZIF socket
address = [10, 9, 8, 7, 6, 5, 4, 3, 39, 38, 35, 37, 2, 40, 41, 1]
# Same as above, data starts at D0, and defines the mapping of the data lines to the ZIF42 socket
data = [11, 12, 13, 29, 30, 31, 32, 33]
# All the pins that must be pulled high to enable this IC
H_enable = []
# All the pins that must be pulled low to enable this IC
L_enable = [34, 36] # /CE and /G
# All the pins that must be pulled high to write to this IC (even though we don't support EPROM programming, we need to disable writing mode when reading)
H_write = [] # We have none
# All the pins that must be pulled low to enable writing
L_write = []

[adapter]
# pins that need to be forced high to read this in the adapter
hi_pins = []
# Notes on the adapter necessary to read this IC
notes = "Insert the IC in the topmost position on the ZIF42, then connect pin 14 to pin 42"

[requirements]
hardware = 3
